version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - json-server

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json
    ports:
      - "3001:3001"
